menu_svg_icons.icon_set_menu.*:
  type: config_entity
  label: 'Icon set menu'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    icon_set:
      type: text
      label: 'Icon set'
