menu_svg_icons.icon_set.*:
  type: config_entity
  label: 'Icon set'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    source:
      type: text
      label: 'Source file'
    placement:
      type: string
      label: 'Icon placement'
    icon_height:
      type: integer
      label: 'Icon height'
    icon_width:
      type: integer
      label: 'Icon width'
